CREATE TABLE [dbo].[Table]
(
	[ID] INT NOT NULL PRIMARY KEY, 
    [BARANGAY] VARCHAR(50) NULL, 
    [CITY] VARCHAR(50) NULL, 
    [PROVINCE] VARCHAR(50) NULL, 
    [ZIPCODE] VARCHAR(5) NULL, 
    [LOGO] VARCHAR(50) NULL
)
